### ISSUE TITLE
A question about dataset

### ISSUE THREAD

**Issue by yaoshentao** [thaolmk54/hcrn-videoqa#1]
I would like to ask you, in the extracted features, such a sentence is given.
![Snipaste_2020-04-06_09-29-15](https://user-images.githubusercontent.com/27396613/78515627-1a447200-77e9-11ea-8cd5-fb28e23501c2.png).
Are the features you extracted only for action tasks?
And if I want to extract all the features, how long will it take to finish?
Thank you!

**Comment by thaolmk54** [comment]
Hi there,

Thank you for your interest in our work.
Currently only extracted features for the action task are available. I can upload the rest for you if needed.

In case you want to extract features yourself from scratch, it might take over a day or so to finish depending on you computer.

Cheers!

**Comment by yaoshentao** [comment]
If you have time, I hope to get the trained features from you. I am very grateful for your gift.

**Comment by thaolmk54** [comment]
Hi,

Extracted features for all tasks in TGIF-QA dataset are now available to download. Thanks.

**Comment by yaoshentao** [comment]
Hi, 
I appreciate your reply. If you have free time, I hope I can get your trained features.
Thanks!

**Comment by yaoshentao** [comment]
Thank you!

**Comment by thaolmk54** [comment]
Hi,

Actually training can be done in a couple of hours so you can do it yourself. I've had my pretrained models here so I will publicly upload them to the same link as provided when I have some time today.

Best of luck with your research.

**Comment by yaoshentao** [comment]
Hi,
I've already seen it. Thank you for sharing. I also hope to see more of your new ideas.
