### ISSUE TITLE
MSRVTT-QA dataset  some videos loss  

### ISSUE THREAD

**Issue by orangehc** [thaolmk54/hcrn-videoqa#10]
Hi, thanks for sharing the repo and your work. When I need to use the source video of MSRVTT-QA, I found some provided urls are invalid now. Could you share the source video of MSRVTT-QA? Thanks a lot.

**Comment by thaolmk54** [comment]
Hi, thanks for your interest in my repo. For MSRVTT-QA and MSVD-QA, you can download videos from the json file provided by the original author of MSRVTT dataset. Otherwise, try this: https://www.mediafire.com/folder/h14iarbs62e7p/shared

Hope this helps.

**Comment by orangehc** [comment]
You helped me a lot, thank you very much！
