### ISSUE TITLE
Video Processing

### ISSUE THREAD

**Issue by huan-end** [thaolmk54/hcrn-videoqa#15]
![image](https://user-images.githubusercontent.com/65533667/131234832-9d11b959-c787-4344-8a5e-6cb8ea8c2a14.png)
![image](https://user-images.githubusercontent.com/65533667/131235019-a71fd657-e758-43bb-b749-cb810ef04534.png)
![image](https://user-images.githubusercontent.com/65533667/131234918-956abdbf-9172-4efd-b260-324d3109fd64.png)

This problem occurred when I modified the video path and tried to process the data. The path was modified, but why did the video read error?
Also, I want to know if the annotations file is under this link? The link is https://mega.nz/file/UnRnyb7A#es4XmqsLxl-B7MP0KAat9VibkH7J_qpKj9NcxLh8aHg

**Comment by thaolmk54** [comment]
Hi there,

It's most likely that the video processing package that you installed has a problem. Which version of scikit-video are you using?

Regarding your question about the annotation file, yes, that is the one I used for my experiments.
