### ISSUE TITLE
Data error

### ISSUE THREAD

**Issue by yaoshentao** [thaolmk54/hcrn-videoqa#2]
I'm sorry to bother you again. After I downloaded your data of frame_qa and merged it into an h5 file, I got an unexpected error. The other task files are right. I am not sure whether the file is damaged due to my download error or the original file you uploaded is wrong. If possible, can you test whether your original file can be read using h5py. It will take me a whole day to re-download your data, thank you.
![image](https://user-images.githubusercontent.com/27396613/79422772-0a4e3e80-7ff0-11ea-9e05-c5f3d93919e1.png)

**Comment by thaolmk54** [comment]
Hi,

Sorry for the issue you got. I will re-upload those files sometime today.

**Comment by yaoshentao** [comment]
Thank you very much

**Comment by thaolmk54** [comment]
Hi,

I've reuploaded the files. I joined the split files in my local PC and they worked just fine though.

**Comment by yaoshentao** [comment]
Hi,
Sorry for wasting your precious time due to my mistake. I will download it again. Thank you!
