### ISSUE TITLE
A question of glove?

### ISSUE THREAD

**Issue by yaoshentao** [thaolmk54/hcrn-videoqa#4]
Hi, 
![image](https://user-images.githubusercontent.com/27396613/81141308-d20ea000-8f9e-11ea-8ce5-d5225979021f.png)
This is your pre-processing question file. The file read in is glove.6B.300d.txt, but the download [link](http://nlp.stanford.edu/data/glove.840B.300d.zip) you gave is glove.840B.300d.txt.
The file I trained data with was glove.6B.300d.txt last time, and did not use the link you gave.

**Comment by thaolmk54** [comment]
Hi, 

Thanks for pointing this out.
It should be glove.840B.300d.txt and the *.pkl file should be glove.840.300d.pkl subsequently.
All of my reported results in the paper are with 840B.300. I will update the python file accordingly.

**Comment by thaolmk54** [comment]
I've corrected the python file.

**Comment by yaoshentao** [comment]
okay！
