### ISSUE TITLE
A problem of accuracy

### ISSUE THREAD

**Issue by yaoshentao** [thaolmk54/hcrn-videoqa#5]
Hi,
I re-downloaded all your files and trained them four times. I completely follow your readme file to train, but the accuracy of the action task  is only about 73%  . If you need to view the log file, I can send it to you. And I tried both in 1080ti and 2080ti and got the same result.
![image](https://user-images.githubusercontent.com/27396613/81281245-28a5d800-908c-11ea-9a4b-c0165e2632d4.png)

**Comment by thaolmk54** [comment]
Hi,

Did you mean accuracy on val set? The results in the paper were on the test set. Please run the validation file (validation.py) to evaluate trained models on the test set.

**Comment by yaoshentao** [comment]
Hi,
I'm so stupid, thank you for your patience.

**Comment by thaolmk54** [comment]
Glad you sorted it out. Cheers!
