### ISSUE TITLE
Another way of downloading the tgif dataset

### ISSUE THREAD

**Issue by RyanLiut** [thaolmk54/hcrn-videoqa#6]
Hi,
    Thank you for your work! I want to run the code, but when I download the dataset tgif by the links from the tsv file, it always fails. Do you have another way to download it? Like Google Drive or other cloud disks?

**Comment by thaolmk54** [comment]
Hi,

Thank you for the question. Not sure how did you download the tsv files? I believe you can easily clone the GitHub repo at https://github.com/YunseokJANG/tgif-qa which contains all tsv files needed for feature extraction.

Sorry that I'm not able to upload those files to cloud services as I'm not authorized to do so. In case you have trouble downloading it, I would recommend you to reach out to the authors of TGIF-QA dataset for assistance.

Regards,

**Comment by RyanLiut** [comment]
Thank you for your reply!
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
