### ISSUE TITLE
About the mutli-choice task in t-gif qa

### ISSUE THREAD

**Issue by eustcPL** [thaolmk54/hcrn-videoqa#8]
Hello, thanks a lot for sharing your impressive work. 

I notice you use the candidate answers information on MC tasks, in _HCRNNetwork.forward_
`out = self.output_unit(question_embedding[batch_agg], q_visual_embedding[batch_agg], ans_candidates_embedding,a_visual_embedding)`. 

So, I tried to use the candidate answer information to guide the _visual_embedding_. I  change the code in `HCRNNetwork.forward` as follows:

```
ans_candidates_agg = ans_candidates.view(-1, ans_candidates.size(2))  
ans_candidates_len_agg = ans_candidates_len.view(-1)
batch_agg = np.reshape(
                np.tile(np.expand_dims(np.arange(batch_size), axis=1), [1, 5]), [-1])
ans_candidates_embedding = self.linguistic_input_unit(ans_candidates_agg, ans_candidates_len_agg)
ans_candidates_emb_mul = ans_candidates_embedding.view(batch_size, 5, -1).sum(1)
question_embedding = self.linguistic_input_unit(question, question_len)
visual_embedding = self.visual_input_unit(video_appearance_feat, video_motion_feat, 
             question_embedding+ans_candidates_emb_mul)
q_visual_embedding = self.feature_aggregation(question_embedding, visual_embedding)
a_visual_embedding = self.feature_aggregation(ans_candidates_embedding, visual_embedding[batch_agg])
out = self.output_unit(question_embedding[batch_agg], q_visual_embedding[batch_agg],
                           ans_candidates_embedding, a_visual_embedding).
```

I get the acurracy of **0.9380** and **0.9759** on the _action_ and _trasition_ task . I checked the loss fuction and acurracy evaluation function and I did not find any bug. Can you explain it?

**Comment by eustcPL** [comment]
I found the problem. 

```
ans_candidates_agg = ans_candidates.view(-1, ans_candidates.size(2))  
ans_candidates_len_agg = ans_candidates_len.view(-1)
batch_agg = np.reshape(
                np.tile(np.expand_dims(np.arange(batch_size), axis=1), [1, 5]), [-1])
ans_candidates_embedding = self.linguistic_input_unit(ans_candidates_agg, ans_candidates_len_agg)
ans_candidates_emb_mul = ans_candidates_embedding.view(batch_size, 5, -1).sum(1)
out = self.output_unit(ans_candidates_embedding, ans_candidates_emb_mul[batch_agg])
```
Only concatenating the **ans_candidates_embedding** and **ans_candidates_emb_mul[batch_agg]** can make the results strange.

**Comment by Fly2flies** [comment]
> I found the problem.
> 
> ```
> ans_candidates_agg = ans_candidates.view(-1, ans_candidates.size(2))  
> ans_candidates_len_agg = ans_candidates_len.view(-1)
> batch_agg = np.reshape(
>                 np.tile(np.expand_dims(np.arange(batch_size), axis=1), [1, 5]), [-1])
> ans_candidates_embedding = self.linguistic_input_unit(ans_candidates_agg, ans_candidates_len_agg)
> ans_candidates_emb_mul = ans_candidates_embedding.view(batch_size, 5, -1).sum(1)
> out = self.output_unit(ans_candidates_embedding, ans_candidates_emb_mul[batch_agg])
> ```
> 
> Only concatenating the **ans_candidates_embedding** and **ans_candidates_emb_mul[batch_agg]** can make the results strange.

Do you change the `OutputUnitMultiChoices` code to fit the input dimensions?
