### ISSUE TITLE
MSRVTT-QA, MSVD-QA dataset

### ISSUE THREAD

**Issue by ghost** [thaolmk54/hcrn-videoqa#9]
hello, Thank you for your excellent work. 
I would like to know if you are willing to provide preprocessed features of MSRVTT-QA and MSVD-QA datasets? I want to test your model on MSRVTT-QA, MSVD-QA dataset.

**Comment by thaolmk54** [comment]
Hi,
Thank you for your interest in our work. You should be able to download the extracted features for those datasets here https://bit.ly/2TX9rlZ.

**Comment by ghost** [comment]
Hi, 
thanks for your sharing!
